# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(909, 670)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.littlebtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.littlebtn.setFont(font)
        self.littlebtn.setObjectName("littlebtn")
        self.gridLayout.addWidget(self.littlebtn, 3, 2, 1, 1)
        self.carolbtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.carolbtn.setFont(font)
        self.carolbtn.setObjectName("carolbtn")
        self.gridLayout.addWidget(self.carolbtn, 3, 0, 1, 1)
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label2.setFont(font)
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 2, 1, 1, 1)
        self.jinglebtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.jinglebtn.setFont(font)
        self.jinglebtn.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"border: 3px solid black;")
        self.jinglebtn.setObjectName("jinglebtn")
        self.gridLayout.addWidget(self.jinglebtn, 3, 1, 1, 1)
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label1.setFont(font)
        self.label1.setAutoFillBackground(False)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "The Bell Hoppers"))
        self.littlebtn.setText(_translate("MainWindow", "Little Drummer Boy"))
        self.carolbtn.setText(_translate("MainWindow", "Carol of the Bells"))
        self.label2.setText(_translate("MainWindow", "Click button!"))
        self.jinglebtn.setText(_translate("MainWindow", "Jingle Bells"))
        self.label1.setText(_translate("MainWindow", "Choose a christmas song to play!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
